# Generated by Django 3.2.9 on 2021-12-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50)),
                ('coursestartdate', models.DateField()),
                ('courseenddate', models.DateTimeField(blank=True, null=True)),
                ('assignementsnum', models.IntegerField(blank=True, null=True)),
                ('materialsnum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('examdate', models.DateTimeField()),
                ('examtimestart', models.TimeField()),
                ('examtimeend', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.courses')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('lecture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lecturesname', models.TextField(blank=True, null=True)),
                ('lectureinfo', models.TextField(blank=True, null=True)),
                ('lectureformat', models.CharField(blank=True, max_length=9, null=True)),
                ('lecturedate', models.DateTimeField()),
                ('lecturetimestart', models.TimeField()),
                ('lecturetimeend', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.courses')),
            ],
            options={
                'db_table': 'lectures',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teachercredentials', models.TextField(blank=True, null=True)),
                ('teacherphonenumber', models.TextField(blank=True, null=True)),
                ('teacheremail', models.TextField(blank=True, null=True)),
                ('courses', models.ManyToManyField(to='dbapp.Courses')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.exams')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('recording_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recordingdateofcreation', models.DateTimeField()),
                ('recordingtype', models.CharField(blank=True, max_length=9, null=True)),
                ('recordinginfo', models.TextField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.lectures')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.IntegerField(primary_key=True, serialize=False)),
                ('materialinfo', models.TextField(blank=True, null=True)),
                ('materiallink', models.TextField(blank=True, null=True)),
                ('materialinsides', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.courses')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.AddField(
            model_name='lectures',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.recordings'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignmenttype', models.CharField(blank=True, max_length=17, null=True)),
                ('assignmentinfo', models.TextField(blank=True, null=True)),
                ('assignmentdeadline', models.DateField(blank=True, null=True)),
                ('assignmentstatus', models.CharField(blank=True, max_length=18, null=True)),
                ('lectures', models.ManyToManyField(to='dbapp.Lectures')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
    ]
