# Generated by Django 3.2.9 on 2021-12-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='assignementsnum',
            new_name='assignmentsnum',
        ),
    ]
