# Generated by Django 3.2.9 on 2021-12-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.courses'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assignmentinfo'], name='assignment_assignm_3d07c4_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['coursename'], name='courses_coursen_f7c606_idx'),
        ),
        migrations.AddIndex(
            model_name='exams',
            index=models.Index(fields=['examdate'], name='exams_examdat_08089a_idx'),
        ),
        migrations.AddIndex(
            model_name='lectures',
            index=models.Index(fields=['lecturesname'], name='lectures_lecture_9db8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='materials',
            index=models.Index(fields=['materialinfo'], name='materials_materia_6acbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacherfullname'], name='teacher_teacher_5d8635_idx'),
        ),
    ]
